### ISSUE TITLE
build problem

### ISSUE THREAD

**Issue by iDoka** [vdudouyt/sdcc-examples-stm8#1]
Hello!

I try build this example with latest version of tools:
http://master.dl.sourceforge.net/project/sdcc/snapshot_builds/sdcc-src/sdcc-src-20140202-8938.tar.bz2
http://citylan.dl.sourceforge.net/project/hex2bin/hex2bin/Hex2bin-1.0.10.tar.bz2

but I have a build-error:

```
[doka@doka sdcc-examples-stm8]$ make
sdcc -mstm8 --out-fmt-ihx   blinky.c
hex2bin -p 00 blinky.ihx
hex2bin v1.0.10, Copyright (C) 2012 Jacques Pelletier & contributors

Lowest address  = 00008000
Highest address = 000080BF
Pad Byte        = 0
8-bit Checksum = BC
/opt/sdcc-3.3.2/bin/sdcc -mstm8 --out-fmt-ihx   uart.c

?ASlink-Warning-Undefined Global '_strlen' referenced by module 'uart'
make: *** [uart.ihx] Error 1
rm uart.ihx blinky.ihx
[doka@doka sdcc-examples-stm8]$ 
```

Also I try pass to sdcc arguments:

```
-I/opt/sdcc-3.3.2/share/sdcc/include -L/opt/sdcc-3.3.2/share/sdcc/lib/stm8
```

This is no changes.

What I doing wrong?

Best Regards,
Doka

**Comment by vdudouyt** [comment]
Hello,

I fixed that with 5229167a02.

Best Regards,

Valentin
